name: SweetSpotYoga
favicon: null
layout_spectrum: 0.14690024754963815
typography_spectrum: 0.5907333199866116
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8799537473823875
  lightness: 0.5500828379299492
  saturation: 0.1726888194680214
  rhythmicContrast: 0.6387367055285722
purpose: []
